### PR TITLE
Set admin user permissions directly

### PR DESCRIPTION
**Pull request by dylanmccall**
`FacilityUser.objects.create_superuser` sets properties which don't make
sense for regular admin users. This changes `DesktopUser.create_user` to
always use `FacilityUser.objects.create_user`, adding roles as required.

### CODE REVIEW

**Review by manuq — APPROVED** [review]
Looks good. Please mention in the commit message for which ticket is this change, then feel free to merge.

**Comment by manuq** [comment]
> Looks good. Please mention in the commit message for which ticket is this change, then feel free to merge.

@dylanmccall let's keep things organized in Phab tickets. This change wasn't verifyed and I think it regressed the case for regular system users.

**Comment by dylanmccall** [comment]
Ack, I meant to link this with https://phabricator.endlessm.com/T32805 since it's a relevant cleanup, but apparently I didn't actually push that change. I'll leave a comment over there :)

**Comment by manuq** [comment]
> Ack, I meant to link this with https://phabricator.endlessm.com/T32805 since it's a relevant cleanup, but apparently I didn't actually push that change. I'll leave a comment over there :)

Yeah no problem. Would you like to verify if this regressed the behavior?

**Comment by dylanmccall** [comment]
Testing this on my end, this seemed to be working correctly (after building `org.learningequality.Kolibri with this change, since testing this stuff with the `.Devel` version is rather tedious), but when trying to create a regular user it's failing here:

```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/lib/python3.8/site-packages/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/lib/python3.8/site-packages/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/lib/python3.8/site-packages/kolibri/dist/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/lib/python3.8/site-packages/kolibri/dist/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/lib/python3.8/site-packages/kolibri_desktop_auth_plugin/views.py", line 12, in get
    user = authenticate(token=token)
  File "/app/lib/python3.8/site-packages/kolibri/dist/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/app/lib/python3.8/site-packages/kolibri/dist/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/app/lib/python3.8/site-packages/kolibri_desktop_auth_plugin/backends.py", line 45, in authenticate
    user = DesktopUser.objects.get_or_create(**user_details)
  File "/app/lib/python3.8/site-packages/kolibri_desktop_auth_plugin/models.py", line 21, in get_or_create
    try:
  File "/app/lib/python3.8/site-packages/kolibri_desktop_auth_plugin/models.py", line 62, in create_user
    DevicePermissions.objects.create(
  File "/app/lib/python3.8/site-packages/kolibri/dist/django/utils/functional.py", line 239, in inner
    return func(self._wrapped, *args)
  File "/app/lib/python3.8/site-packages/kolibri/dist/configobj.py", line 554, in __getitem__
    val = dict.__getitem__
```

Which is strange! I was thinking maybe the defaults weren't being added to the options dictionary here, but it looks like it just doesn't load. Might be something I'm doing wrong - i have a terrible headache today so haven't been able to look at it in any detail.

**Pull request merged**
